import "./globals.css";
import { Analytics } from "@vercel/analytics/react"
import CustomCursor from "@/components/CustomCursor";
import InteractiveBackground from "@/components/fullbg";
import { Exo } from 'next/font/google'

const exo_init = Exo({ subsets: ['latin'] ,
  weight: ['400']
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${exo_init.className}`}
      >
        <Analytics />
        <CustomCursor />
        <InteractiveBackground />
        {children}
      </body>
    </html>
  );
}
